version: '3.1'
services:
  portainer:
    restart: always
    image: portainer/portainer:latest
    container_name: portainer
    ports:
    - 8000:8000
    - 9400:9000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /portainer_data:/data portainer/portainer
volumes:
  portainer_data: {}
