apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:
    name: phpmyadmin
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      name: phpmyadmin
  template:
    metadata:      
      labels:
        name: phpmyadmin
    spec:
      containers:
      - env:
        - name: PMA_HOSTS
          value: mysql
        image: phpmyadmin/phpmyadmin        
        name: phpmyadmin
        ports:
        - containerPort: 80
        resources:
          requests:  
            cpu: 100m       
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 2G
